[global]
database_url = "/home/manu/solarmeter/db/solar_db.db"
create_database = true
web_server_port = 8081
bind_address = "0.0.0.0"

[location]
city = "Berlin"
timezone = "Europe/Berlin"
latitude = 48.1351
longitude = 11.5820

[meters.SDM72D_1]
name = "SDM72D_M_1"
port = "/dev/ttyACM0"
baud_rate = 9600
timeout = 10
polling_rate = 5
type = "sdm72d"
modbus_address = 1

#[meters.SDM72D_2]
#name = "SDM72D_M_2"
#type = "sdm72d"
#modbus_address = 2

#[meters.mock_meter]
#name = "Mock_Solar_1"
#type = "mock"
#modbus_address = 3
#min_power = -5000.0
#max_power = 5000.0
#power_variation = 500.0
