version: '3.8'

services:
  solarmeter:
    image: sbnhndrt/solarlogger:latest
    container_name: solarmeter
    restart: unless-stopped
    devices:
      - /dev/tty:/dev/ttyACM0  # Adjust this based on your USB device
    volumes:
      - ./config:/app/config
      - ./db:/app/db
      - ./logs:/var/log/solar_meter
    ports:
      - "8081:8081"  # Web server port
    environment:
      - CONFIG_PATH=/app/config/config.toml

#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    restart: unless-stopped
#    volumes:
#      - ./prometheus:/etc/prometheus
#      - prometheus_data:/prometheus
#    ports:
#      - "9090:9090"
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--storage.tsdb.path=/prometheus'
#      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
#      - '--web.console.templates=/usr/share/prometheus/consoles'
#
#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana
#    restart: unless-stopped
#    volumes:
#      - grafana_data:/var/lib/grafana
#    ports:
#      - "3000:3000"
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=admin  # Change this in production
#
#volumes:
#  prometheus_data:
#  grafana_data: